### PR TITLE
SVG icon sheet task, demo, and docs

### PR DESCRIPTION
**Pull request by synapticism**

### CODE REVIEW

**Comment by synapticism** [comment]
If you like the approach I can try applying it to 2.0, just let me know how you'd want to handle it (if you do).

One other thing I noticed is that you've got screen reader text embedded in `span` elements. With `svg` you can add semantic `title` and `desc` elements instead (as well as appropriate WAI-ARIA attributes) for greater accessibility.

**Comment by greypants** [comment]
Thanks! Looks great at first glance. When I get a chance to test it out, I'll give more feedback, or merge it.

**Comment by greypants** [comment]
Just letting you know I haven't forgot about this. Just tried it out on a project and love it. This will make it in. I might tweak the docs and task names a tiny bit. Thanks for this!

**Comment by synapticism** [comment]
Awesome :+1:

**Comment by greypants** [comment]
A version of this is in 2.0 now! Thanks for your help. I took out the cheerio bit because I like to have more fine grained control and sometimes want to leave a fill on there, set some to `currentColor` so you can style multiple colors.

**Pull request closed without merging**
