### PR TITLE
Use iconFont as dependency to avoid build errors on production

### PR DESCRIPTION
**Pull request by rwam**
The iconFont task takes to long and it leads to wrong builds or build errors. Have a look at our output from jenkins:

    + gulp production
    [15:35:14] Using gulpfile ~/.jenkins/jobs/…/assets/gulpfile.js
    [15:35:14] Starting 'production'...
    [15:35:14] Starting 'markup'...
    [15:35:14] Starting 'images'...
    [15:35:14] Starting 'iconFont'...
    [15:35:14] Starting 'sass'...
    [15:35:14] Starting 'browserify'...
    [15:35:14] Bundling main.js...
    [15:35:14] Finished 'production' after 137 ms
    [15:35:14] gulp-imagemin: Minified 0 images
    [15:35:14] Finished 'images' after 138 ms
    [15:35:14] gulp-notify: [Compile Error] Error in plugin 'gulp-sass'
    Message:
        src/sass/main.scss
      3:9  file to import not found or unreadable: icons
    Current dir:
    Details:
        column: 9
        line: 3
        file: stdin
        status: 1
        messageFormatted: src/sass/main.scss
      3:9  file to import not found or unreadable: icons
    Current dir:
    [15:35:14] gulp-notify: [Error running notifier] Could not send message: not found: notify-send
    [15:35:14] Finished 'sass' after 187 ms
    [15:35:14] Starting 'minifyCss'...
    [15:35:14] Finished 'minifyCss' after 11 ms
    [15:35:14] Finished 'markup' after 277 ms
    [15:35:15] Finished 'browserify' after 777 ms
    [15:35:15] Starting 'uglifyJs'...
    [15:35:15] Size main.js : 643 B
    [15:35:15] Finished 'uglifyJs' after 149 ms
    [15:35:16] gulp-svgicons2svgfont: Font created
    [15:35:16] Finished 'iconFont' after 1.93 s

At the sass task there is no icons partial available. To solve this use the iconFont task as dependency for the production task.

### CODE REVIEW

**Comment by rwam** [comment]
The same for the default task.

**Comment by rwam** [comment]
We are using Jenkins to build the project. The partial _icons.sass must be not a part of the repository, because it will generate by the iconFont task.

**Comment by greypants** [comment]
Thanks! All good notes. I'll get some form of this in soon.

**Comment by greypants** [comment]
This is handled already in the 2.0 branch. I'll go ahead and merge this into master, but I'm about to overwrite that wit 2.0. I'll save the old browserify version to a 1.0 branch, with this commit in there.

**Pull request merged**
