### PR TITLE
Add JS testing framework: Karma w/ Mocha, Chai and Sinon

### PR DESCRIPTION
**Pull request by greypants**
image

### CODE REVIEW

**Comment by nhunzaker** [comment]
:+1:

**Comment by aboutlo** [comment]
Cool! I don't like too much the directory layout but it's fair enough ;)

**Comment by greypants** [comment]
@aboutlo We picked up the directory structure from Facebook's [Jest](https://facebook.github.io/jest/). We're not using Jest so much anymore, but have been doing a lot of React at Viget lately, and the pattern's gaining traction. Or at least @nhunzaker assures me it is ;)

**Comment by aboutlo** [comment]
hehe yes I know from where __test__ comes. No worries ;)

**Pull request merged**
